name: Create and publish a Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-node-18-debian:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ckcr4lyf/node-sslconf-poc-node18

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          VERSION: 18

  build-and-push-node-20-debian:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ckcr4lyf/node-sslconf-poc-node20

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          VERSION: 20

  build-and-push-patched-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ckcr4lyf/node-sslconf-poc-patched-node

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: node-patched.Dockerfile

  node-18-debian:
    runs-on: ubuntu-latest
    needs: build-and-push-node-18-debian
    name: Test on Node 18 (Debian)

    steps:
      - name: Run the image without any env (expect success)
        uses: docker://ghcr.io/ckcr4lyf/node-sslconf-poc-node18:master

      - name: Run the image with EXTRA CA CERTS (expect failure)
        uses: docker://ghcr.io/ckcr4lyf/node-sslconf-poc-node18:master
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt

  node-20-debian:
    runs-on: ubuntu-latest
    needs: build-and-push-node-20-debian
    name: Test on Node 20 (Debian)

    steps:
      - name: Run the image without any env (expect success)
        uses: docker://ghcr.io/ckcr4lyf/node-sslconf-poc-node20:master

      - name: Run the image with EXTRA CA CERTS (expect failure)
        uses: docker://ghcr.io/ckcr4lyf/node-sslconf-poc-node20:master
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt     

  patched-node:
    runs-on: ubuntu-latest
    needs: build-and-push-patched-node
    name: Test on Patched Node

    steps:
      - name: Run the image without any env (expect success)
        uses: docker://ghcr.io/ckcr4lyf/node-sslconf-poc-patched-node:master

      - name: Run the image with EXTRA CA CERTS (expect success! PATCHED!)
        uses: docker://ghcr.io/ckcr4lyf/node-sslconf-poc-patched-node:master
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt               
           
