name: Failure examples from "normal" clients

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: node server.mjs &
    - name: Test with cURL
      continue-on-error: true
      run: curl -v https://127.0.0.1:4433
    - name: Test with OpenSSL
      continue-on-error: true
      run: openssl s_client -connect 127.0.0.1:4433
    - name: Test with NodeJS
      continue-on-error: true
      run: node client.mjs